//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONFIGURATION
    {
        public System.Guid CONFIGURATIONID { get; set; }
        public string CONFIGURATIONKEY { get; set; }
        public string CONFIGURATINVALUESTRING { get; set; }
        public Nullable<int> CONFIGURATIONVALUEINT { get; set; }
        public Nullable<bool> CONFIGURATIONVALUEBOOL { get; set; }
        public Nullable<System.Guid> CONFIGURATIONVALUEGUID { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    }
}
