CREATE TABLE TBL_ACCOUNTS(
	ACCOUNTID UNIQUEIDENTIFIER NOT NULL,
	[FIRSTNAME] NVARCHAR(50) NOT NULL,
	[MIDDLENAME] NVARCHAR(50) NOT NULL,
	[LASTNAME] NVARCHAR(50) NOT NULL,
	[EMAIL] NVARCHAR(50) NOT NULL,
	[USERNAME] NVARCHAR(50) NOT NULL,
	[PASSWORD] NVARCHAR(50) NOT NULL,
	[CREATEDDATE] DATETIME NOT NULL,
	[CREATEDBY] NVARCHAR(50) NULL,
	[UPDATEDDATE] DATETIME NULL,
	[UPDATEDBY] NVARCHAR(50) NULL,
	CONSTRAINT PK_TBL_ACCOUNT_ACCOUNTID PRIMARY KEY NONCLUSTERED(
		ACCOUNTID ASC
	) ON [PRIMARY],
	CONSTRAINT UQ_TBL_ACCOUNT_NAME UNIQUE NONCLUSTERED(
		FIRSTNAME ASC,
		MIDDLENAME ASC,
		LASTNAME ASC
	) ON [PRIMARY]
)

ALTER TABLE TBL_ACCOUNTS ADD CONSTRAINT DF_TBL_ACCOUNT_ACCOUNTID DEFAULT (NEWID()) FOR ACCOUNTID
ALTER TABLE TBL_ACCOUNTS ADD CONSTRAINT DF_TBL_ACCOUNT_CREATEDDATE DEFAULT (GETDATE()) FOR CREATEDDATE