CREATE TABLE TBL_ENVIRONMENTDATA(
	ENVIRONMENTDATEID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	EDID INT NOT NULL IDENTITY(1,1),
	HUMIDITY INT NOT NULL DEFAULT 0,
	AMMONIA INT NOT NULL DEFAULT 0,
	SULFURDIOXICE INT NOT NULL DEFAULT 0,
	TEMPERATURE INT NOT NULL DEFAULT 0,
	CARBONMONOXIDE INT NOT NULL DEFAULT 0,
	NITROGENOXIDE INT NOT NULL DEFAULT 0,
	ISDISPLAYED BIT NOT NULL DEFAULT 0,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
) ON [PRIMARY]
