CREATE TABLE TBL_CONFIGURATION(
	CONFIGURATIONID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	CONFIGURATIONKEY NVARCHAR(50) NOT NULL,
	CONFIGURATINVALUESTRING NVARCHAR(50) NULL,
	CONFIGURATIONVALUEINT INT NULL,
	CONFIGURATIONVALUEBOOL BIT NULL,
	CONFIGURATIONVALUEGUID UNIQUEIDENTIFIER NULL,
	CREATEDDATE DATETIME NOT NULL DEFAULT GETDATE(),
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL
) ON [PRIMARY]


