CREATE TABLE TBL_ACTIVATION(
	[ACTIVATIONID] UNIQUEIDENTIFIER NOT NULL,
	[CODE] NVARCHAR(6) NOT NULL,
	[EMAIL] NVARCHAR(50) NOT NULL,
	[CREATEDDATE] DATETIME NOT NULL,
	[CREATEDBY] NVARCHAR(50) NULL,
	[UPDATEDDATE] DATETIME NULL,
	[UPDATEDBY] NVARCHAR(50) NULL,
	CONSTRAINT PK_ACTIVATIONID PRIMARY KEY NONCLUSTERED(
		ACTIVATIONID ASC
	) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE TBL_ACTIVATION ADD CONSTRAINT DF_TBL_ACTIVATION_ACTIVATIONID DEFAULT(NEWID()) FOR ACTIVATIONID
ALTER TABLE TBL_ACTIVATION ADD CONSTRAINT DF_TBL_ACTIVATION_CREATEDDATE DEFAULT(GETDATE()) FOR CREATEDDATE